services:
  blinkbridge:
    build: .
    container_name: blinkbridge
    restart: unless-stopped
    ports:
    - 10.20.0.19:8765:8765
    volumes:
    - ./config:/config
    - /mnt/pool1/stacks/blinkbridge/working:/working
    tty: true
    environment:
    - BLINKBRIDGE_CONFIG=/config/config.json
    - TZ=Europe/Berlin
    networks:
      default: null
    image: blinkbridge-blinkbridge
  mediamtx:
    image: bluenviron/mediamtx
    container_name: mediamtx
    restart: unless-stopped
    environment:
    - MTX_RTSPTRANSPORTS=tcp
    - MTX_WRITEQUEUESIZE=2048
    - TZ=Europe/Berlin
    volumes:
    - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    ports:
    - 10.20.0.19:8556:8554/tcp
    networks:
      default: null
      frigate-streams:
        aliases:
        - blink-mtx
networks:
  default: {}
  frigate-streams:
    external: true
    name: frigate-streams
